title: Cape Cod Trail Running
description: A guide to running and biking the trails on Cape Cod
theme: just-the-docs

url: https://capecodtrailrunning.com

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: 
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  routes:
    permalink: "/:collection/:path/"
    output: true
  trailheads:
    permalink: "/:collection/:path/"
    output: true 

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    routes:
      # Give the collection a name
      name: Trail Routes
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true
    trailheads:
      # Give the collection a name
      name: Trailheads
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true
