title: Cape Cod Trail Running
description: A guide to running and biking the trails on Cape Cod
theme: just-the-docs

url: https://capecodtrailrunning.com

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: 
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# Define Jekyll collections
collections:
  towns:
    permalink: "/:path/"
    output: true

just_the_docs:
  collections:
    towns:
      # Give the collection a name
      name: Towns
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true